"""initial schema

Revision ID: 6370679c8050
Revises: 
Create Date: 2026-04-13 21:55:42.658788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6370679c8050'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_type', sa.String(length=3), nullable=False),
    sa.Column('mbti_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('weaknesses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_type', 'mbti_code', name='uq_personality_type')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_type', sa.String(length=3), nullable=False),
    sa.Column('dimension', sa.String(length=3), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_type', 'dimension', 'order_num', name='uq_question')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.String(length=8), nullable=False),
    sa.Column('pet_type', sa.String(length=3), nullable=False),
    sa.Column('mbti_code', sa.String(length=4), nullable=False),
    sa.Column('score_ei', sa.Integer(), nullable=False),
    sa.Column('score_sn', sa.Integer(), nullable=False),
    sa.Column('score_tf', sa.Integer(), nullable=False),
    sa.Column('score_jp', sa.Integer(), nullable=False),
    sa.Column('pct_ei', sa.Integer(), nullable=False),
    sa.Column('pct_sn', sa.Integer(), nullable=False),
    sa.Column('pct_tf', sa.Integer(), nullable=False),
    sa.Column('pct_jp', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_index('ix_test_results_created_at', 'test_results', ['created_at'], unique=False)
    op.create_index('ix_test_results_share_id', 'test_results', ['share_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_results_share_id', table_name='test_results')
    op.drop_index('ix_test_results_created_at', table_name='test_results')
    op.drop_table('test_results')
    op.drop_table('questions')
    op.drop_table('personality_types')
    # ### end Alembic commands ###
