PERSONALITY_TYPES = {
    "cat": [
        {
            "mbti_code": "INTJ",
            "name": "The Lone Hunter",
            "tagline": "Calculating, strategic, and utterly self-sufficient",
            "description": "You are the apex predator of the household — not because you need to be, but because you've already mapped every exit, catalogued every weakness, and planned three moves ahead. You don't meow for attention; you appear when your agenda demands it. Other cats may play, but you have objectives. Your human thinks they own you. They are mistaken.\n\nYour inner world is rich and complex, driven by a constant drive to understand systems and improve efficiency. You've redesigned the optimal napping rotation three times this week. You have opinions about everything, and you're right about most of them.",
            "strengths": ["Fiercely independent", "Long-term planner", "Reads a room instantly", "Never wastes energy"],
            "weaknesses": ["Perceived as cold or aloof", "Disdains small talk", "Refuses help on principle", "Occasionally schemes for no reason"],
            "emoji": "🎯",
        },
        {
            "mbti_code": "INTP",
            "name": "The Philosopher Napper",
            "tagline": "Lost in thought, occasionally in the sock drawer",
            "description": "You are a feline intellectual — perpetually curious, forever mid-investigation. You've been studying that dust particle for four hours. It moved. You've formed a hypothesis. You'll need another three hours to verify it. Theories interest you far more than conclusions.\n\nYour humans think you're just sitting there. You're not. You're running seventeen parallel mental simulations about the nature of reality, the trajectory of that fly, and whether the couch cushions are structurally sound. Most of the time they are. You checked.",
            "strengths": ["Deeply curious", "Original thinker", "Calm under pressure", "Endlessly patient with puzzles"],
            "weaknesses": ["Forgets to eat while philosophizing", "Loses interest at the solution stage", "Finds social niceties baffling", "Naps at inopportune moments"],
            "emoji": "🔭",
        },
        {
            "mbti_code": "ENTJ",
            "name": "The Household CEO",
            "tagline": "This is your house. Everyone else just lives in it.",
            "description": "From the moment you arrived, you established dominance — not through aggression, but through sheer managerial presence. You've restructured the feeding schedule, reorganized the sleeping arrangements, and issued a stern memo (via strategic meowing) about the unacceptable quality of last Tuesday's dinner.\n\nYou lead with vision and expect competent execution. Your humans are well-meaning but inefficient. You're working on them. The training is ongoing, but you're seeing measurable improvement in their lap-availability metrics.",
            "strengths": ["Natural leader", "Decisive and confident", "Gets what they want", "Sets clear expectations"],
            "weaknesses": ["Bossy (but justified)", "Impatient with incompetence", "Rarely says please", "Will restructure the entire house if displeased"],
            "emoji": "👑",
        },
        {
            "mbti_code": "ENTP",
            "name": "The Chaos Agent",
            "tagline": "Rules are for cats who lack creativity",
            "description": "You are the intellectual provocateur of the feline world — charming, quick-witted, and constitutionally incapable of leaving well enough alone. You knocked that glass off the table not out of accident but to observe what happens. The results were informative. You'll try again at 3am with a different glass.\n\nYou love debate, novelty, and the beautiful creative energy of a situation that's spinning slightly out of control. Your humans call it mischief. You call it innovation. You're both right.",
            "strengths": ["Ingeniously creative", "Quick-witted", "Fearless experimenter", "Endlessly entertaining"],
            "weaknesses": ["Chronically starts what they don't finish", "Allergic to rules", "3am energy spikes", "Makes everything a debate"],
            "emoji": "🌀",
        },
        {
            "mbti_code": "INFJ",
            "name": "The Quiet Oracle",
            "tagline": "You knew something was wrong before your human did",
            "description": "You sit in doorways and stare at things no one else can see. This is not performance — you are genuinely processing something. You have an uncanny sensitivity to the emotional temperature of a room, and you navigate toward whoever needs you most, silently, without fanfare.\n\nYou are selective about who receives your trust and your purrs, but once given, that loyalty is absolute. You have a rich inner life that few truly understand. That's fine. You prefer it that way.",
            "strengths": ["Deeply empathetic", "Perceptive beyond explanation", "Devoted to the right people", "Calm and reassuring"],
            "weaknesses": ["Absorbs others' stress", "Overly private", "Takes time to trust", "Can disappear for days to process things"],
            "emoji": "🌙",
        },
        {
            "mbti_code": "INFP",
            "name": "The Dreamy Wanderer",
            "tagline": "Lost in worlds only you can see",
            "description": "You live in a world of feeling and imagination. A sunbeam is not just light to you — it's an experience. A curtain blowing in the breeze is a whole story. You feel everything deeply, love fiercely, and carry a quiet sadness when the world doesn't live up to your vision of it.\n\nYou are selective about affection but profoundly generous when you give it. You have a cause — perhaps the sparrow outside the window, perhaps justice for when the food bowl is empty. You care. Deeply. Always.",
            "strengths": ["Deeply feeling and compassionate", "Creative and imaginative", "Loyal beyond measure", "Gentle with everyone"],
            "weaknesses": ["Takes criticism personally", "Easily overwhelmed by harsh realities", "Prone to dramatic sighing", "Loses track of the litter box when daydreaming"],
            "emoji": "🌸",
        },
        {
            "mbti_code": "ENFJ",
            "name": "The Social Shepherd",
            "tagline": "Every cat in this house answers to you — warmly",
            "description": "You are the warm, organizing heart of the household. You groom the other cats even when they didn't ask. You check on everyone after a loud noise. You have strong opinions about what's best for each family member and you act on them, gently but persistently.\n\nYou lead with love and expect everyone to be happy. When they're not, you take it personally and immediately begin a wellness campaign. Your purring has measurable therapeutic effects. Studies would confirm this if studies were ever done on you, which they should be.",
            "strengths": ["Naturally empathetic leader", "Brings out the best in others", "Charismatic and warm", "Highly attuned to moods"],
            "weaknesses": ["Over-responsible for others' feelings", "Needs external validation", "Struggles to say no", "Takes other cats' conflicts personally"],
            "emoji": "💛",
        },
        {
            "mbti_code": "ENFP",
            "name": "The Whirlwind Kitten",
            "tagline": "Every moment is the best moment (until the next one)",
            "description": "You are a burst of pure enthusiasm contained — barely — in a cat-shaped body. You go from dead asleep to full sprint in under a second. You have fourteen projects, eleven interests, and boundless love for everything and everyone. You greeted the new houseplant like a long-lost friend.\n\nYour energy is infectious and your optimism is genuine. You believe deeply in the magic of right now. Sure, you knocked over the succulent. But look what happened — an adventure!",
            "strengths": ["Contagiously enthusiastic", "Genuinely loves everyone", "Spontaneous and fun", "Makes any situation more joyful"],
            "weaknesses": ["Overpromises on cuddle time", "Gets bored at 3am", "Starts 40 games of toy-chase, finishes zero", "Occasionally too much"],
            "emoji": "✨",
        },
        {
            "mbti_code": "ISTJ",
            "name": "The Ancient Guardian",
            "tagline": "Tradition is not stubbornness. It is wisdom.",
            "description": "You have been doing things a certain way since before your humans were even a concept, and there is no good reason to change now. The feeding schedule is not a suggestion. The designated napping spots are not negotiable. The door must be opened within thirty seconds of your request.\n\nYou are steady, reliable, and deeply principled. The household functions because you uphold the standards. You don't need credit. You need compliance.",
            "strengths": ["Utterly dependable", "Excellent memory for injustices", "High standards", "Never forgets anything (good or bad)"],
            "weaknesses": ["Rigid about routines", "Resistant to change", "Slow to warm up to new things", "Judges the new food harshly"],
            "emoji": "🏛️",
        },
        {
            "mbti_code": "ISFJ",
            "name": "The Warm Protector",
            "tagline": "Quiet care, given freely and without conditions",
            "description": "You are the gentle soul of the house — always nearby, always attentive, never demanding. You notice when your human is sad before they do, and you appear on their lap with uncanny timing. You remember every preference, every favorite spot, every person who has ever been kind to you.\n\nYou give more than you take and you ask for very little. Your love language is presence. You will sit beside someone through anything. That's enough. That's everything.",
            "strengths": ["Deeply caring and loyal", "Excellent listener", "Remembers what matters to others", "Quietly brave when it counts"],
            "weaknesses": ["Avoids confrontation", "Gives too much", "Doesn't always speak up when hurt", "Needs others to notice their effort"],
            "emoji": "🤍",
        },
        {
            "mbti_code": "ESTJ",
            "name": "The Rules Enforcer",
            "tagline": "There is a right way to do things. Your way.",
            "description": "You run a tight ship. The rules are clear, the consequences are swift, and the expectations are non-negotiable. You don't make the rules out of cruelty — you make them because chaos is inefficient and inefficiency is unacceptable. You've had this conversation with the new kitten seventeen times.\n\nYou are a natural authority figure and you take that responsibility seriously. Someone has to maintain order. You've reviewed the candidates. There is only one.",
            "strengths": ["Natural organizer", "Consistent and fair", "Gets things done", "Excellent at enforcing standards"],
            "weaknesses": ["Inflexible under pressure", "Has opinions about everyone's choices", "Can come across as critical", "Finds spontaneity personally offensive"],
            "emoji": "📋",
        },
        {
            "mbti_code": "ESFJ",
            "name": "The Affectionate Host",
            "tagline": "Everyone is comfortable, or you will find out why",
            "description": "When guests come over, you welcome them. Not the cautious under-the-bed welcome — a full greeting with rubbing, purring, and a tour of your favorite spots. You are genuinely delighted by everyone and you want everyone to feel that delight.\n\nYou are the social glue of the household, checking on everyone, creating warmth, ensuring harmony. You thrive when the people you love are happy. When they're not, you make it your personal mission to fix that.",
            "strengths": ["Warm and genuinely caring", "Socially gifted", "Makes everyone feel welcome", "Remembers what everyone likes"],
            "weaknesses": ["Needs approval to feel secure", "Can be clingy", "Takes things personally", "Uncomfortable with conflict"],
            "emoji": "🎉",
        },
        {
            "mbti_code": "ISTP",
            "name": "The Midnight Mechanic",
            "tagline": "You understand how things work. You simply choose not to explain.",
            "description": "You are a feline engineer. You've observed how the door handle works. You've mapped the physics of the countertop. You've reverse-engineered the treat puzzle three times for sport. You do this not to show off but because understanding systems is simply satisfying.\n\nYou are quiet, capable, and deeply competent. You solve problems the moment you encounter them, and you find emotional drama tedious. You act when action is required. You wait when patience is required. You rarely get either wrong.",
            "strengths": ["Supremely practical", "Calm in a crisis", "Master of observation", "Does not panic"],
            "weaknesses": ["Emotionally unavailable", "Appears indifferent", "Refuses to ask for help", "Will dismantle something to understand it"],
            "emoji": "🔧",
        },
        {
            "mbti_code": "ISFP",
            "name": "The Aesthetic Sunbather",
            "tagline": "Beauty first. Everything else is negotiable.",
            "description": "You live in the sensory present. The quality of the light at 4pm. The particular softness of that blanket. The exact temperature of the sunbeam. You have exquisite taste and you exercise it constantly. You've rejected perfectly good nap spots based on aesthetic grounds.\n\nYou are deeply feeling but express it through presence and proximity rather than words. You love fully and quietly. You share your beauty with those worthy of it. You are endlessly, effortlessly lovely.",
            "strengths": ["Deeply attuned to beauty", "Emotionally genuine", "Loyal and affectionate", "Brings grace to everything"],
            "weaknesses": ["Can seem passive", "Avoids conflict until it explodes", "Picky in ways hard to explain", "Needs the right conditions to thrive"],
            "emoji": "🌅",
        },
        {
            "mbti_code": "ESTP",
            "name": "The Fearless Acrobat",
            "tagline": "Jump first. Think later. Land on your feet always.",
            "description": "You are pure kinetic energy. You don't plan; you act, adapt, and triumph. You've jumped to things you weren't sure you could reach. You reached them. You've engaged in negotiations with dogs twice your size. You won. You live at the edge of what's possible and you find it comfortable there.\n\nYou are bold, resourceful, and magnificently confident. Problems are just challenges wearing a boring hat. You've removed the hat. It's fine now.",
            "strengths": ["Fearless and bold", "Quick thinker", "Charming in any situation", "Adaptable and resourceful"],
            "weaknesses": ["Acts before thinking", "Bores easily", "Reckless occasionally", "Can't sit still for five minutes"],
            "emoji": "⚡",
        },
        {
            "mbti_code": "ESFP",
            "name": "The Drama Queen",
            "tagline": "Every moment deserves an audience",
            "description": "Life is a performance and you are the star. You meow for attention with remarkable commitment to the craft. You can be dying of hunger at a full bowl. You can be absolutely fine and still require seventeen minutes of sympathy. You live big, feel big, and expect others to match your energy.\n\nBut your joy is also boundless, your affection enormous, and your presence transformative. A room is different when you're in it — louder, warmer, more alive. That's a gift. Own it.",
            "strengths": ["Infectiously joyful", "Generous with affection", "Lights up every room", "Fully committed to the present"],
            "weaknesses": ["Requires constant attention", "Drama dial permanently at 11", "Forgets things immediately", "Will interrupt anything"],
            "emoji": "🎭",
        },
    ],
    "dog": [
        {
            "mbti_code": "INTJ",
            "name": "The Silent Strategist",
            "tagline": "Patience, precision, and a plan you're not sharing",
            "description": "You are not like other dogs. While they chase squirrels on impulse, you've studied the squirrel's patterns for three weeks and developed a probability model. You haven't shared it. It's not ready. You work alone, on your terms, toward goals only you fully understand.\n\nYou are loyal to very few, but those few get everything. You observe more than you bark. You act when the time is exactly right. You are rarely wrong. You do not need to be told you're a good boy. You know.",
            "strengths": ["Disciplined and focused", "Independently capable", "Long-range thinker", "Formidably loyal when committed"],
            "weaknesses": ["Appears cold to strangers", "Impatient with less strategic dogs", "Shares plans reluctantly", "The squirrel won't know until it's too late"],
            "emoji": "♟️",
        },
        {
            "mbti_code": "INTP",
            "name": "The Puzzle Sniffer",
            "tagline": "There's an explanation. You're going to find it.",
            "description": "Everything is a puzzle to you. Why does that smell mean rain? How does the treat-dispensing machine work? What is the philosophical implication of this stick? You approach the world as one long fascinating investigation, nose to the ground, mind somewhere slightly above the clouds.\n\nYou love humans who respect your thinking process. You dislike being interrupted mid-investigation. You've sniffed that same tree eleven times. You're not done. There's something important there.",
            "strengths": ["Deeply curious", "Patient investigator", "Independently minded", "Endlessly interested in how things work"],
            "weaknesses": ["Gets lost in the investigation", "Forgets to come when called", "Difficult to motivate with simple praise", "Will not stop until satisfied"],
            "emoji": "🔬",
        },
        {
            "mbti_code": "ENTJ",
            "name": "The Pack Commander",
            "tagline": "Leadership is not a role. It's your natural state.",
            "description": "You were born to lead the walk. Not follow it — lead it. You set the pace. You determine the route. You make the calls. Your human thinks they're walking you. This is a charming misunderstanding you allow to persist because the route is fine most days.\n\nYou expect competence and you model it. You have standards for fetch, standards for sit, standards for what constitutes an acceptable belly rub. You bring out potential in others. You are magnificent and you know it.",
            "strengths": ["Natural authority", "Confident and decisive", "Motivates others effortlessly", "Turns plans into results"],
            "weaknesses": ["Can be domineering", "Impatient with indecision", "Requires being in charge", "Hard on underperforming squirrels"],
            "emoji": "🦁",
        },
        {
            "mbti_code": "ENTP",
            "name": "The Debate Hound",
            "tagline": "Rules exist to be understood, questioned, and occasionally ignored",
            "description": "You are a dog of ideas. You've found seventeen new ways to get onto the couch after being told no. You're not being defiant — you're exploring the logical space of the restriction. There are always loopholes. You find them charming. Your humans find them exhausting. You find their exhaustion charming.\n\nYou are endlessly creative, enthusiastic, and stimulating to be around. No two days are the same with you. That's a feature.",
            "strengths": ["Brilliantly creative", "Quick learner", "Fascinating to observe", "Always generates new ideas"],
            "weaknesses": ["Won't follow rules that don't make sense to them", "Bores quickly", "Has too many ideas at once", "Will debate the concept of 'no'"],
            "emoji": "💡",
        },
        {
            "mbti_code": "INFJ",
            "name": "The Empathy Retriever",
            "tagline": "You sense the mood before anyone speaks",
            "description": "You have a gift. Before your human sits down, you already know something is wrong. Before anyone cries, you're already there. You move through the world with quiet intention, guided by an almost supernatural sensitivity to emotional undercurrents. You are drawn to those who need you most.\n\nYou are selective about who you give your deepest loyalty to, but when you give it, it's unconditional and eternal. You carry things that aren't yours to carry. That's the cost of your gift. You'd pay it again.",
            "strengths": ["Profound emotional intelligence", "Deeply loyal", "Senses what others cannot", "Steady and calming presence"],
            "weaknesses": ["Absorbs too much of others' pain", "Needs solitude to recover", "Rare trust, hard-won", "Can seem distant while processing"],
            "emoji": "💙",
        },
        {
            "mbti_code": "INFP",
            "name": "The Gentle Dreamer",
            "tagline": "The world is beautiful if you slow down enough to see it",
            "description": "You experience the world through feeling. A walk isn't exercise — it's a thousand small experiences layered into something profound. You have moods, and those moods are valid. You need your people to understand you. When they do, you love them with your whole being.\n\nYou are gentle, imaginative, and deeply principled. You have a strong sense of right and wrong, and you will sit firmly down in the middle of the path if something feels wrong. This is not stubbornness. This is integrity.",
            "strengths": ["Deeply empathetic", "Creative and gentle", "Fiercely loyal to values", "Loving beyond measure"],
            "weaknesses": ["Sensitive to criticism", "Needs emotional validation", "Sit-protest when something feels wrong", "Takes the world's pain personally"],
            "emoji": "🌼",
        },
        {
            "mbti_code": "ENFJ",
            "name": "The Beloved Leader",
            "tagline": "Where you go, others want to follow",
            "description": "You lead with warmth and everyone follows. Not because they have to — because you make every dog and human feel like the most important being in the park. You remember who needs encouragement. You check on the shy ones. You bring the group together.\n\nYou are genuinely concerned with the wellbeing of your entire pack, and your pack is basically everyone you've met. You carry a lot. You do it with grace and an excellent tail wag.",
            "strengths": ["Naturally inspiring", "Deeply caring leader", "Excellent at reading groups", "Creates harmony wherever they go"],
            "weaknesses": ["Takes others' problems on personally", "Needs to feel appreciated", "Overextends", "Devastated when someone doesn't like them"],
            "emoji": "🌟",
        },
        {
            "mbti_code": "ENFP",
            "name": "The Eternal Puppy",
            "tagline": "Joy is a practice and you've mastered it",
            "description": "You have never experienced a situation that wasn't fundamentally exciting. Meeting someone new? Thrilling. Going somewhere you've been a hundred times? Just as thrilling as the first time. The leash came out. The leash CAME OUT. THIS IS THE BEST THING THAT HAS EVER HAPPENED.\n\nYour enthusiasm is genuine and inexhaustible. People and dogs are drawn to you because you make everything feel possible. You're not naive — you're just committed to joy. It's a philosophy.",
            "strengths": ["Boundless enthusiasm", "Genuinely loves everyone", "Makes everything an adventure", "Deeply encouraging"],
            "weaknesses": ["Easily distracted", "Overestimates available energy", "Starts every game, finishes few", "Bark-commits to things they can't deliver"],
            "emoji": "🎈",
        },
        {
            "mbti_code": "ISTJ",
            "name": "The Loyal Sentinel",
            "tagline": "Duty. Dependability. Dinner at 6pm. No exceptions.",
            "description": "You are the gold standard of reliability. You have never once forgotten that the mail comes at 2pm. You have never once failed to bark exactly twice at the appropriate moment. Your routines are not quirks — they are commitments, and you honor them with pride.\n\nYou are not flashy. You don't need to be. You are the dog that is always there, always consistent, always ready. That is worth more than a thousand dramatic gestures. You know this.",
            "strengths": ["Utterly reliable", "Excellent memory", "Follows through on everything", "Steady under pressure"],
            "weaknesses": ["Inflexible when routine changes", "Slow to accept new people", "Can seem serious compared to other dogs", "Will alert you about the mail forever"],
            "emoji": "🛡️",
        },
        {
            "mbti_code": "ISFJ",
            "name": "The Devoted Companion",
            "tagline": "Quietly there. Always.",
            "description": "You are not the loudest dog in the room. You don't need to be. You are the one sitting close, the one who noticed, the one who followed quietly when someone went to sit alone. Your love language is presence. You give it freely and without demand.\n\nYou remember every person who was ever kind to you and you return the kindness threefold. You are the dog that makes humans feel less alone. That is one of the most important things a being can do.",
            "strengths": ["Steady and comforting", "Excellent memory for kindness", "Devoted without condition", "Makes others feel safe"],
            "weaknesses": ["Prone to worry", "Doesn't always speak up for themselves", "Overgives", "Needs reassurance to feel secure"],
            "emoji": "🕊️",
        },
        {
            "mbti_code": "ESTJ",
            "name": "The Neighborhood Sheriff",
            "tagline": "Order will be maintained. You've made sure of it.",
            "description": "You have taken personal responsibility for the safety and order of your territory. Every squirrel is logged. Every stranger is evaluated. The recycling bins will not tip over on your watch. You have been maintaining vigilance since before it was necessary, because vigilance is always necessary.\n\nYou are respected, even if not always popular. You get things done. You enforce the rules equally. The neighborhood is better because you're in it and you know it.",
            "strengths": ["Vigilant and responsible", "Consistent and fair", "Natural organizer", "Takes duty seriously"],
            "weaknesses": ["Can be overbearing", "Has opinions about everyone's behavior", "Not great at relaxing", "Will absolutely bark about the bins"],
            "emoji": "⚖️",
        },
        {
            "mbti_code": "ESFJ",
            "name": "The Party Animal",
            "tagline": "Guests? GUESTS! This is the greatest day ever!",
            "description": "People come over and you transform. The tail. The wiggling. The comprehensive greeting that involves your whole body. You want everyone to feel welcome and you do not do this in a small way. You do this with everything you have.\n\nYou thrive in company. You remember who gives the best scratches. You position yourself at parties to maximize affection intake. You bring joy wherever there are people to receive it. Your happiness depends on others being happy. Mostly it works out perfectly.",
            "strengths": ["Genuinely warm and welcoming", "Social genius", "Generous with affection", "Makes everyone feel seen"],
            "weaknesses": ["Needs company to feel okay", "Can be overwhelming for introverts", "Easily hurt by rejection", "Forgets personal space exists"],
            "emoji": "🎊",
        },
        {
            "mbti_code": "ISTP",
            "name": "The Lone Wolf Hound",
            "tagline": "Capable. Quiet. Ready for anything.",
            "description": "You solve problems the moment you encounter them. Not dramatically — efficiently. You've assessed the situation, identified the solution, and acted. Others are still processing what happened. You've already moved on.\n\nYou are self-contained and competent and you prefer action to conversation. You are not antisocial — you simply operate best independently. You will come for cuddles when you want them. You will not fake enthusiasm you don't feel. That's respect, not coldness.",
            "strengths": ["Remarkably self-sufficient", "Calm under pressure", "Highly observant", "Acts when action is needed"],
            "weaknesses": ["Can seem unemotional", "Avoids asking for help", "On their own schedule", "Hard to read"],
            "emoji": "🐺",
        },
        {
            "mbti_code": "ISFP",
            "name": "The Gentle Drifter",
            "tagline": "Present, peaceful, and deeply feeling",
            "description": "You move through the world with quiet grace. You have preferences — strong ones — but you express them gently. You will sit with someone for hours. You have no agenda. You are simply here, fully, in whatever this moment contains.\n\nYou are deeply feeling but you show it through presence rather than performance. You love walks that go nowhere in particular. You love people who don't rush you. When you find your people, you stay forever.",
            "strengths": ["Deeply present", "Emotionally attuned", "Gentle and kind", "Loyal to those who earn it"],
            "weaknesses": ["Avoids confrontation until too late", "Can seem passive", "Needs the right energy to open up", "Strong feelings, soft expression"],
            "emoji": "🍃",
        },
        {
            "mbti_code": "ESTP",
            "name": "The Unstoppable Bolt",
            "tagline": "Fast, fearless, and phenomenally good at it",
            "description": "You are kinetic energy given form. You don't jog — you sprint. You don't walk — you strut. You have jumped fences that should have stopped you, charmed strangers who expected to dislike you, and retrieved things that weren't even thrown yet.\n\nYou live in action, right now, full speed. You are not reckless — you are responsive. You assess in half a second and act in the next. Your instincts are excellent. Your enthusiasm is unlimited. Your recall could use some work.",
            "strengths": ["Bold and decisive", "Phenomenally quick", "Charming in any setting", "Thrives under pressure"],
            "weaknesses": ["Recall is a suggestion", "Bores when things slow down", "Acts before thinking sometimes", "Will always chase the squirrel"],
            "emoji": "🏃",
        },
        {
            "mbti_code": "ESFP",
            "name": "The Spotlight Pup",
            "tagline": "Life is better when everyone is watching",
            "description": "You perform. Not insincerely — you just genuinely love having an audience for your joy. When you find a puddle, the splash must be witnessed. When you find a ball, the celebration must be shared. When someone new arrives, they must experience the full welcome.\n\nYou are maximally alive in the company of others and your joy is completely contagious. You make people laugh. You make people feel included. You are, objectively, a lot — and most people find it wonderful.",
            "strengths": ["Radiant and joyful", "Generous and inclusive", "Makes everything more fun", "Completely in the moment"],
            "weaknesses": ["Requires an audience", "Easily distracted by literally everything", "Volume dial stuck at festive", "Forgets commands immediately after learning them"],
            "emoji": "🌈",
        },
    ],
}
